# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('short_key', models.SlugField(max_length=4, primary_key=True, serialize=False)),
                ('full_url', models.URLField(max_length=300)),
                ('creation_date', models.DateTimeField(auto_now=True)),
                ('count', models.IntegerField(default=0)),
            ],
        ),
    ]
