# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-05 10:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookmarks', '0002_auto_20160404_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='mod_date',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 4, 5, 10, 18, 38, 427935, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmark',
            name='title',
            field=models.CharField(default=datetime.datetime(2016, 4, 5, 10, 18, 52, 171154, tzinfo=utc), max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
